version: '3.8'

services:
  api-gateway:
    image: nginx:alpine
    container_name: mirage-api-gateway
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"  # Monitoring port
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
      - nginx-cache:/var/cache/nginx
      # SSL certs would go here in production
      # - ./certs:/etc/nginx/certs:ro
    environment:
      - MIRAGE_ENV=${MIRAGE_ENV:-production}
      - NGINX_HOST=${NGINX_HOST:-localhost}
      - NGINX_PORT=${NGINX_PORT:-80}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - mirage-network

networks:
  mirage-network:
    external: true

volumes:
  nginx-cache:
