apiVersion: apps/v1
kind: Deployment
metadata:
  name: correlation-engine-service
  namespace: mirage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: correlation-engine-service
  template:
    metadata:
      labels:
        app: correlation-engine-service
    spec:
      containers:
      - name: correlation-engine-service
        image: ghcr.io/van1sh/Mirage/correlation-engine-service:latest
        ports:
        - containerPort: 8087
        env:
        - name: NEO4J_URI
          value: "bolt://neo4j:7687"
        - name: NEO4J_USERNAME
          value: "neo4j"
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: password
        - name: DATA_STORAGE_URL
          value: "http://data-storage-service:8086"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8087
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: correlation-engine-service
  namespace: mirage
spec:
  selector:
    app: correlation-engine-service
  ports:
  - port: 8087
    targetPort: 8087
  type: ClusterIP
