apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  namespace: mirage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui
        image: ghcr.io/van1sh/Mirage/web-ui:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: http://api-gateway:8080
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: mirage
spec:
  selector:
    app: web-ui
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
